# Generated by Django 4.1.3 on 2022-11-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='spicy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
