# Generated by Django 4.1.3 on 2022-11-10 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_spicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='spicy',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
