# Generated by Django 4.1.3 on 2022-11-10 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_spicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='spicy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
